name: Build modules

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build_prx:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      zip: '${{ github.workspace }}/plugins.zip'
      zip_glob_path: 'bin/plugins/prx'
      zip_glob: '*.prx'
      build_tag: 'build_${{ github.run_number }}'
      hen_path: hen

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Checkout hen
      uses: actions/checkout@v4
      with:
        path: ${{ env.hen_path }}
        repository: MexrlDev/PS4-Hen

    - name: Setup variables
      run: |
        sudo apt install -y llvm lld unzip p7zip-full
        echo "commit_ver=1.$(git rev-list HEAD --count)" >> $GITHUB_ENV
        echo "commit_hash=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: Download OpenOrbis Toolchain
      run: |
        f=toolchain-llvm-18.2
        curl -fLJO https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/releases/download/v0.5.3/$f.zip
        unzip $f.zip
        tar -xzf toolchain-llvm-18.tar.gz -C ./
        ls .
        echo "OO_PS4_TOOLCHAIN=$PWD/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV

    - name: Build all modules
      run: bash build.sh

    - name: Zip
      working-directory: ${{ env.zip_glob_path }}
      run: 7z a ${{ env.zip }} ${{ env.zip_glob }} ${{ github.workspace }}/LICENSE ${{ github.workspace }}/plugin_server/LICENSE.plugin_server.txt

    - name: Copy plugins
      working-directory: ${{ env.hen_path }}
      run: |
        t=tmp
        f=plugins.zip
        mkdir -p $t
        cd $t
        cp -v ${{ env.zip }} $f
        unzip $f

    - name: Build with PS4 Payload SDK
      uses: Scene-Collective/ps4-payload-sdk@main
      with:
        app_path: ${{ env.hen_path }}
        build_command: bash build.sh

    - name: Upload plugins
      uses: actions/upload-artifact@v4
      with:
        name: plugins-${{ env.build_tag }}
        path: |
          ${{ github.workspace }}/${{ env.zip_glob_path }}/${{ env.zip_glob }}
          ${{ github.workspace }}/LICENSE

    - name: Upload HEN with built plugins
      uses: actions/upload-artifact@v4
      with:
        name: hen-plugins-${{ env.build_tag }}
        path: ${{ env.hen_path }}/hen.bin

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create ${{ env.build_tag }} --target ${{ github.sha }} -t "${{ env.build_tag }}" -p --generate-notes

    - name: Upload plugins.zip to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ env.build_tag }} ${{ env.zip }}

    - name: Upload hen.bin to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ env.build_tag }} ${{ env.hen_path }}/hen.bin
